import ssl
ssl._create_default_https_context = ssl._create_unverified_context
import urllib.request as request
import re
import bs4
import pyperclip as ppc
import tkinter as tk

window = tk.Tk()
window.title('Exchange Rate in Taiwan App')
window.geometry('1000x630')
window.configure(background='white')

src="https://rate.bot.com.tw/xrt/fltxt/0/day"
with request.urlopen(src) as response:
    data=response.read().decode("UTF-8-sig")
data=re.sub(r"[ ]+",r" ",data)
data=data.split('\r\n')
data.remove(data[0])
datac=[re.sub(r"^([A-Z]+).+$",r"\1",i) for i in data]

src="https://rate.bot.com.tw/xrt"
with request.urlopen(src) as response:
    Date=response.read().decode("utf-8")
Date=bs4.BeautifulSoup(Date, "html.parser")
Date=Date.find_all("span", class_="time")
Date='牌價最新掛牌時間：'+re.sub(r".+\>(.+)\<.+",r"\1",str(Date))

Date_label = tk.Label(window, text=Date,font=('',13))
Date_label.pack()


def zeroc(x):
    if x==0:
        x=x+100000000000000000
    return x

def zerostr(x):
    a=float(x)
    if a==0:
        x='---'
    return x

def z1(x):
    a=zerostr(format(x,'.5f'))
    return a

def z2(x,y):
    a=zerostr(format(y/zeroc(x),'.5f'))
    return a

def z3(x,y):
    a=zerostr(format(x*y,'.3f'))
    return a

def exx(x):
    ppc.copy(x)
    return


datam=[re.sub(r".+本行賣出 ([.0-9]+) .+$",r"\1",i) for i in data]
data1=list(zip(datac,datam))
d = {}
for key, value in data1:
    if key not in d:
        d[key] = []
    d[key].append(value)
ex_USD=float(d['USD'][0])
ex_HKD=float(d['HKD'][0])
ex_GBP=float(d['GBP'][0])
ex_AUD=float(d['AUD'][0])
ex_CAD=float(d['CAD'][0])
ex_SGD=float(d['SGD'][0])
ex_CHF=float(d['CHF'][0])
ex_JPY=float(d['JPY'][0])
ex_ZAR=float(d['ZAR'][0])
ex_SEK=float(d['SEK'][0])
ex_NZD=float(d['NZD'][0])
ex_THB=float(d['THB'][0])
ex_PHP=float(d['PHP'][0])
ex_IDR=float(d['IDR'][0])
ex_EUR=float(d['EUR'][0])
ex_KRW=float(d['KRW'][0])
ex_VND=float(d['VND'][0])
ex_MYR=float(d['MYR'][0])
ex_CNY=float(d['CNY'][0])

ex_USD_1=z1(ex_USD)
ex_HKD_1=z1(ex_HKD)
ex_GBP_1=z1(ex_GBP)
ex_AUD_1=z1(ex_AUD)
ex_CAD_1=z1(ex_CAD)
ex_SGD_1=z1(ex_SGD)
ex_CHF_1=z1(ex_CHF)
ex_JPY_1=z1(ex_JPY)
ex_ZAR_1=z1(ex_ZAR)
ex_SEK_1=z1(ex_SEK)
ex_NZD_1=z1(ex_NZD)
ex_THB_1=z1(ex_THB)
ex_PHP_1=z1(ex_PHP)
ex_IDR_1=z1(ex_IDR)
ex_EUR_1=z1(ex_EUR)
ex_KRW_1=z1(ex_KRW)
ex_VND_1=z1(ex_VND)
ex_MYR_1=z1(ex_MYR)
ex_CNY_1=z1(ex_CNY)

header_label = tk.Label(window, text='《 臺灣銀行公告  現金匯率  本行賣出價 》', font=('',16))
header_label.pack(side=tk.TOP)
header2_label = tk.Label(window, text='( 一元各國貨幣 您需使用多少新台幣去買進 )', font=('',13))
header2_label.pack(side=tk.TOP)
space_label = tk.Label(window, text='    ', font=('',2))
space_label.pack(side=tk.TOP)
ex_frame = tk.Frame(window)
ex_frame.pack(side=tk.TOP)
ex1_label = tk.Label(ex_frame, text='①美金(USD)：NT$', font=('',14))
ex1_label.grid(row=0, column=0,sticky=tk.E)
ex1_button = tk.Button(ex_frame, text=ex_USD_1, command=lambda: exx(ex_USD_1))
ex1_button.grid(row=0, column=1, padx=1,sticky=tk.E)
ex2_label = tk.Label(ex_frame, text='②港幣(HKD)：NT$', font=('',14))
ex2_label.grid(row=0, column=2,sticky=tk.E)
ex2_button = tk.Button(ex_frame, text=ex_HKD_1, command=lambda: exx(ex_HKD_1))
ex2_button.grid(row=0, column=3, padx=1,sticky=tk.E)
ex3_label = tk.Label(ex_frame, text='③英鎊(GBP)：NT$', font=('',14))
ex3_label.grid(row=0, column=4,sticky=tk.E)
ex3_button = tk.Button(ex_frame, text=ex_GBP_1, command=lambda: exx(ex_GBP_1))
ex3_button.grid(row=0, column=5, padx=1,sticky=tk.E)
ex4_label = tk.Label(ex_frame, text='④澳幣(AUD)：NT$', font=('',14))
ex4_label.grid(row=0, column=6,sticky=tk.E)
ex4_button = tk.Button(ex_frame, text=ex_AUD_1, command=lambda: exx(ex_AUD_1))
ex4_button.grid(row=0, column=7, padx=1,sticky=tk.E)
ex5_label = tk.Label(ex_frame, text='⑤加拿大幣(CAD)：NT$', font=('',14))
ex5_label.grid(row=1, column=0,sticky=tk.E)
ex5_button = tk.Button(ex_frame, text=ex_CAD_1, command=lambda: exx(ex_CAD_1))
ex5_button.grid(row=1, column=1, padx=1,sticky=tk.E)
ex6_label = tk.Label(ex_frame, text='⑥新加坡幣(SGD)：NT$', font=('',14))
ex6_label.grid(row=1, column=2,sticky=tk.E)
ex6_button = tk.Button(ex_frame, text=ex_SGD_1, command=lambda: exx(ex_SGD_1))
ex6_button.grid(row=1, column=3, padx=1,sticky=tk.E)
ex7_label = tk.Label(ex_frame, text='⑦瑞士法郎(CHF)：NT$', font=('',14))
ex7_label.grid(row=1, column=4,sticky=tk.E)
ex7_button = tk.Button(ex_frame, text=ex_CHF_1, command=lambda: exx(ex_CHF_1))
ex7_button.grid(row=1, column=5, padx=1,sticky=tk.E)
ex8_label = tk.Label(ex_frame, text='⑧日圓(JPY)：NT$', font=('',14))
ex8_label.grid(row=1, column=6,sticky=tk.E)
ex8_button = tk.Button(ex_frame, text=ex_JPY_1, command=lambda: exx(ex_JPY_1))
ex8_button.grid(row=1, column=7, padx=1,sticky=tk.E)
ex9_label = tk.Label(ex_frame, text='⑨南非幣(ZAR)：NT$', font=('',14))
ex9_label.grid(row=2, column=0,sticky=tk.E)
ex9_button = tk.Button(ex_frame, text=ex_ZAR_1, command=lambda: exx(ex_ZAR_1))
ex9_button.grid(row=2, column=1, padx=1,sticky=tk.E)
ex10_label = tk.Label(ex_frame, text='⑩瑞典幣(SEK)：NT$', font=('',14))
ex10_label.grid(row=2, column=2,sticky=tk.E)
ex10_button = tk.Button(ex_frame, text=ex_SEK_1, command=lambda: exx(ex_SEK_1))
ex10_button.grid(row=2, column=3, padx=1,sticky=tk.E)
ex11_label = tk.Label(ex_frame, text='⑪紐元(NZD)：NT$', font=('',14))
ex11_label.grid(row=2, column=4,sticky=tk.E)
ex11_button = tk.Button(ex_frame, text=ex_NZD_1, command=lambda: exx(ex_NZD_1))
ex11_button.grid(row=2, column=5, padx=1,sticky=tk.E)
ex12_label = tk.Label(ex_frame, text='⑫泰幣(THB)：NT$', font=('',14))
ex12_label.grid(row=2, column=6,sticky=tk.E)
ex12_button = tk.Button(ex_frame, text=ex_THB_1, command=lambda: exx(ex_THB_1))
ex12_button.grid(row=2, column=7, padx=1,sticky=tk.E)
ex13_label = tk.Label(ex_frame, text='⑬菲國比索(PHP)：NT$', font=('',14))
ex13_label.grid(row=3, column=0,sticky=tk.E)
ex13_button = tk.Button(ex_frame, text=ex_PHP_1, command=lambda: exx(ex_PHP_1))
ex13_button.grid(row=3, column=1, padx=1,sticky=tk.E)
ex14_label = tk.Label(ex_frame, text='⑭印尼幣(IDR)：NT$', font=('',14))
ex14_label.grid(row=3, column=2,sticky=tk.E)
ex14_button = tk.Button(ex_frame, text=ex_IDR_1, command=lambda: exx(ex_IDR_1))
ex14_button.grid(row=3, column=3, padx=1,sticky=tk.E)
ex15_label = tk.Label(ex_frame, text='⑮歐元(EUR)：NT$', font=('',14))
ex15_label.grid(row=3, column=4,sticky=tk.E)
ex15_button = tk.Button(ex_frame, text=ex_EUR_1, command=lambda: exx(ex_EUR_1))
ex15_button.grid(row=3, column=5, padx=1,sticky=tk.E)
ex16_label = tk.Label(ex_frame, text='⑯韓元(KRW)：NT$', font=('',14))
ex16_label.grid(row=3, column=6,sticky=tk.E)
ex16_button = tk.Button(ex_frame, text=ex_KRW_1, command=lambda: exx(ex_KRW_1))
ex16_button.grid(row=3, column=7, padx=1,sticky=tk.E)
ex17_label = tk.Label(ex_frame, text='⑰越南盾(VND)：NT$', font=('',14))
ex17_label.grid(row=4, column=0,sticky=tk.E)
ex17_button = tk.Button(ex_frame, text=ex_VND_1, command=lambda: exx(ex_VND_1))
ex17_button.grid(row=4, column=1, padx=1,sticky=tk.E)
ex18_label = tk.Label(ex_frame, text='⑱馬來幣(MYR)：NT$', font=('',14))
ex18_label.grid(row=4, column=2,sticky=tk.E)
ex18_button = tk.Button(ex_frame, text=ex_MYR_1, command=lambda: exx(ex_MYR_1))
ex18_button.grid(row=4, column=3, padx=1,sticky=tk.E)
ex19_label = tk.Label(ex_frame, text='⑲人民幣(CNY)：NT$', font=('',14))
ex19_label.grid(row=4, column=4,sticky=tk.E)
ex19_button = tk.Button(ex_frame, text=ex_CNY_1, command=lambda: exx(ex_CNY_1))
ex19_button.grid(row=4, column=5, padx=1,sticky=tk.E)

def ex1():
    money=float(ex_t2f_entry.get())
    t1=z2(ex_USD,money)
    t2=z2(ex_HKD,money)
    t3=z2(ex_GBP,money)
    t4=z2(ex_AUD,money)
    t5=z2(ex_CAD,money)
    t6=z2(ex_SGD,money)
    t7=z2(ex_CHF,money)
    t8=z2(ex_JPY,money)
    t9=z2(ex_ZAR,money)
    t10=z2(ex_SEK,money)
    t11=z2(ex_NZD,money)
    t12=z2(ex_THB,money)
    t13=z2(ex_PHP,money)
    t14=z2(ex_IDR,money)
    t15=z2(ex_EUR,money)
    t16=z2(ex_KRW,money)
    t17=z2(ex_VND,money)
    t18=z2(ex_MYR,money)
    t19=z2(ex_CNY,money)
    window2 = tk.Tk()
    window2.title('新台幣 換成 外幣')
    window2.geometry('1000x205')
    window2.configure(background='white')
    space_ex_label = tk.Label(window2, text='    ', font=('',7))
    space_ex_label.pack(side=tk.TOP)
    theader_label = tk.Label(window2, text='新台幣：'+ex_t2f_entry.get()+'元  可換多少外幣', font=('',21))
    theader_label.pack(side=tk.TOP)
    space_ex_label = tk.Label(window2, text='    ', font=('',7))
    space_ex_label.pack(side=tk.TOP)
    ex_1_frame = tk.Frame(window2)
    ex_1_frame.pack(side=tk.TOP)
    ex_b1_label = tk.Label(ex_1_frame, text='①美金(USD) $', font=('',14))
    ex_b1_label.grid(row=0, column=0,sticky=tk.E)
    ex_b1_button = tk.Button(ex_1_frame, text=t1, command=lambda: exx(t1))
    ex_b1_button.grid(row=0, column=1, padx=1,sticky=tk.E)
    ex_b2_label = tk.Label(ex_1_frame, text='②港幣(HKD) $', font=('',14))
    ex_b2_label.grid(row=0, column=2,sticky=tk.E)
    ex_b2_button = tk.Button(ex_1_frame, text=t2, command=lambda: exx(t2))
    ex_b2_button.grid(row=0, column=3, padx=1,sticky=tk.E)
    ex_b3_label = tk.Label(ex_1_frame, text='③英鎊(GBP) £', font=('',14))
    ex_b3_label.grid(row=0, column=4,sticky=tk.E)
    ex_b3_button = tk.Button(ex_1_frame, text=t3, command=lambda: exx(t3))
    ex_b3_button.grid(row=0, column=5, padx=1,sticky=tk.E)
    ex_b4_label = tk.Label(ex_1_frame, text='④澳幣(AUD) $', font=('',14))
    ex_b4_label.grid(row=0, column=6,sticky=tk.E)
    ex_b4_button = tk.Button(ex_1_frame, text=t4, command=lambda: exx(t4))
    ex_b4_button.grid(row=0, column=7, padx=1,sticky=tk.E)
    ex_b5_label = tk.Label(ex_1_frame, text='⑤加拿大幣(CAD) $', font=('',14))
    ex_b5_label.grid(row=1, column=0,sticky=tk.E)
    ex_b5_button = tk.Button(ex_1_frame, text=t5, command=lambda: exx(t5))
    ex_b5_button.grid(row=1, column=1, padx=1,sticky=tk.E)
    ex_b6_label = tk.Label(ex_1_frame, text='⑥新加坡幣(SGD) $', font=('',14))
    ex_b6_label.grid(row=1, column=2,sticky=tk.E)
    ex_b6_button = tk.Button(ex_1_frame, text=t6, command=lambda: exx(t6))
    ex_b6_button.grid(row=1, column=3, padx=1,sticky=tk.E)
    ex_b7_label = tk.Label(ex_1_frame, text='⑦瑞士法郎(CHF) ₣', font=('',14))
    ex_b7_label.grid(row=1, column=4,sticky=tk.E)
    ex_b7_button = tk.Button(ex_1_frame, text=t7, command=lambda: exx(t7))
    ex_b7_button.grid(row=1, column=5, padx=1,sticky=tk.E)
    ex_b8_label = tk.Label(ex_1_frame, text='⑧日圓(JPY) ¥', font=('',14))
    ex_b8_label.grid(row=1, column=6,sticky=tk.E)
    ex_b8_button = tk.Button(ex_1_frame, text=t8, command=lambda: exx(t8))
    ex_b8_button.grid(row=1, column=7, padx=1,sticky=tk.E)
    ex_b9_label = tk.Label(ex_1_frame, text='⑨南非幣(ZAR) $', font=('',14))
    ex_b9_label.grid(row=2, column=0,sticky=tk.E)
    ex_b9_button = tk.Button(ex_1_frame, text=t9, command=lambda: exx(t9))
    ex_b9_button.grid(row=2, column=1, padx=1,sticky=tk.E)
    ex_b10_label = tk.Label(ex_1_frame, text='⑩瑞典幣(SEK) $', font=('',14))
    ex_b10_label.grid(row=2, column=2,sticky=tk.E)
    ex_b10_button = tk.Button(ex_1_frame, text=t10, command=lambda: exx(t10))
    ex_b10_button.grid(row=2, column=3, padx=1,sticky=tk.E)
    ex_b11_label = tk.Label(ex_1_frame, text='⑪紐元(NZD) $', font=('',14))
    ex_b11_label.grid(row=2, column=4,sticky=tk.E)
    ex_b11_button = tk.Button(ex_1_frame, text=t11, command=lambda: exx(t11))
    ex_b11_button.grid(row=2, column=5, padx=1,sticky=tk.E)
    ex_b12_label = tk.Label(ex_1_frame, text='⑫泰幣(THB) ฿', font=('',14))
    ex_b12_label.grid(row=2, column=6,sticky=tk.E)
    ex_b12_button = tk.Button(ex_1_frame, text=t12, command=lambda: exx(t12))
    ex_b12_button.grid(row=2, column=7, padx=1,sticky=tk.E)
    ex_b13_label = tk.Label(ex_1_frame, text='⑬菲國比索(PHP) ₱', font=('',14))
    ex_b13_label.grid(row=3, column=0,sticky=tk.E)
    ex_b13_button = tk.Button(ex_1_frame, text=t13, command=lambda: exx(t13))
    ex_b13_button.grid(row=3, column=1, padx=1,sticky=tk.E)
    ex_b14_label = tk.Label(ex_1_frame, text='⑭印尼幣(IDR) ₨', font=('',14))
    ex_b14_label.grid(row=3, column=2,sticky=tk.E)
    ex_b14_button = tk.Button(ex_1_frame, text=t14, command=lambda: exx(t14))
    ex_b14_button.grid(row=3, column=3, padx=1,sticky=tk.E)
    ex_b15_label = tk.Label(ex_1_frame, text='⑮歐元(EUR) €', font=('',14))
    ex_b15_label.grid(row=3, column=4,sticky=tk.E)
    ex_b15_button = tk.Button(ex_1_frame, text=t15, command=lambda: exx(t15))
    ex_b15_button.grid(row=3, column=5, padx=1,sticky=tk.E)
    ex_b16_label = tk.Label(ex_1_frame, text='⑯韓元(KRW) ₩', font=('',14))
    ex_b16_label.grid(row=3, column=6,sticky=tk.E)
    ex_b16_button = tk.Button(ex_1_frame, text=t16, command=lambda: exx(t16))
    ex_b16_button.grid(row=3, column=7, padx=1,sticky=tk.E)
    ex_b17_label = tk.Label(ex_1_frame, text='⑰越南盾(VND) ₫', font=('',14))
    ex_b17_label.grid(row=4, column=0,sticky=tk.E)
    ex_b17_button = tk.Button(ex_1_frame, text=t17, command=lambda: exx(t17))
    ex_b17_button.grid(row=4, column=1, padx=1,sticky=tk.E)
    ex_b18_label = tk.Label(ex_1_frame, text='⑱馬來幣(MYR) $', font=('',14))
    ex_b18_label.grid(row=4, column=2,sticky=tk.E)
    ex_b18_button = tk.Button(ex_1_frame, text=t18, command=lambda: exx(t18))
    ex_b18_button.grid(row=4, column=3, padx=1,sticky=tk.E)
    ex_b19_label = tk.Label(ex_1_frame, text='⑲人民幣(CNY) ¥', font=('',14))
    ex_b19_label.grid(row=4, column=4,sticky=tk.E)
    ex_b19_button = tk.Button(ex_1_frame, text=t19, command=lambda: exx(t19))
    ex_b19_button.grid(row=4, column=5, padx=1,sticky=tk.E)

def ex1_b():
    money_b=float(ex_t2fb_entry.get())
    tb1=z3(money_b,ex_USD)
    tb2=z3(money_b,ex_HKD)
    tb3=z3(money_b,ex_GBP)
    tb4=z3(money_b,ex_AUD)
    tb5=z3(money_b,ex_CAD)
    tb6=z3(money_b,ex_SGD)
    tb7=z3(money_b,ex_CHF)
    tb8=z3(money_b,ex_JPY)
    tb9=z3(money_b,ex_ZAR)
    tb10=z3(money_b,ex_SEK)
    tb11=z3(money_b,ex_NZD)
    tb12=z3(money_b,ex_THB)
    tb13=z3(money_b,ex_PHP)
    tb14=z3(money_b,ex_IDR)
    tb15=z3(money_b,ex_EUR)
    tb16=z3(money_b,ex_KRW)
    tb17=z3(money_b,ex_VND)
    tb18=z3(money_b,ex_MYR)
    tb19=z3(money_b,ex_CNY)
    window2_2 = tk.Tk()
    window2_2.title('新台幣 換成 外幣')
    window2_2.geometry('1000x205')
    window2_2.configure(background='white')
    space_ex_b_label = tk.Label(window2_2, text='    ', font=('',7))
    space_ex_b_label.pack(side=tk.TOP)
    theader_b_label = tk.Label(window2_2, text='欲換外幣：'+ex_t2fb_entry.get()+'元  需要多少新台幣', font=('',21))
    theader_b_label.pack(side=tk.TOP)
    space_ex_b_label = tk.Label(window2_2, text='    ', font=('',7))
    space_ex_b_label.pack(side=tk.TOP)
    ex_b_1_frame = tk.Frame(window2_2)
    ex_b_1_frame.pack(side=tk.TOP)
    ex_b_b1_label = tk.Label(ex_b_1_frame, text='①美金(USD)<-NT$', font=('',14))
    ex_b_b1_label.grid(row=0, column=0,sticky=tk.E)
    ex_b_b1_button = tk.Button(ex_b_1_frame, text=tb1, command=lambda: exx(tb1))
    ex_b_b1_button.grid(row=0, column=1, padx=1,sticky=tk.E)
    ex_b_b2_label = tk.Label(ex_b_1_frame, text='②港幣(HKD)<-NT$', font=('',14))
    ex_b_b2_label.grid(row=0, column=2,sticky=tk.E)
    ex_b_b2_button = tk.Button(ex_b_1_frame, text=tb2, command=lambda: exx(tb2))
    ex_b_b2_button.grid(row=0, column=3, padx=1,sticky=tk.E)
    ex_b_b3_label = tk.Label(ex_b_1_frame, text='③英鎊(GBP)<-NT$', font=('',14))
    ex_b_b3_label.grid(row=0, column=4,sticky=tk.E)
    ex_b_b3_button = tk.Button(ex_b_1_frame, text=tb3, command=lambda: exx(tb3))
    ex_b_b3_button.grid(row=0, column=5, padx=1,sticky=tk.E)
    ex_b_b4_label = tk.Label(ex_b_1_frame, text='④澳幣(AUD)<-NT$', font=('',14))
    ex_b_b4_label.grid(row=0, column=6,sticky=tk.E)
    ex_b_b4_button = tk.Button(ex_b_1_frame, text=tb4, command=lambda: exx(tb4))
    ex_b_b4_button.grid(row=0, column=7, padx=1,sticky=tk.E)
    ex_b_b5_label = tk.Label(ex_b_1_frame, text='⑤加拿大幣(CAD)<-NT$', font=('',14))
    ex_b_b5_label.grid(row=1, column=0,sticky=tk.E)
    ex_b_b5_button = tk.Button(ex_b_1_frame, text=tb5, command=lambda: exx(tb5))
    ex_b_b5_button.grid(row=1, column=1, padx=1,sticky=tk.E)
    ex_b_b6_label = tk.Label(ex_b_1_frame, text='⑥新加坡幣(SGD)<-NT$', font=('',14))
    ex_b_b6_label.grid(row=1, column=2,sticky=tk.E)
    ex_b_b6_button = tk.Button(ex_b_1_frame, text=tb6, command=lambda: exx(tb6))
    ex_b_b6_button.grid(row=1, column=3, padx=1,sticky=tk.E)
    ex_b_b7_label = tk.Label(ex_b_1_frame, text='⑦瑞士法郎(CHF)<-NT$', font=('',14))
    ex_b_b7_label.grid(row=1, column=4,sticky=tk.E)
    ex_b_b7_button = tk.Button(ex_b_1_frame, text=tb7, command=lambda: exx(tb7))
    ex_b_b7_button.grid(row=1, column=5, padx=1,sticky=tk.E)
    ex_b_b8_label = tk.Label(ex_b_1_frame, text='⑧日圓(JPY)<-NT$', font=('',14))
    ex_b_b8_label.grid(row=1, column=6,sticky=tk.E)
    ex_b_b8_button = tk.Button(ex_b_1_frame, text=tb8, command=lambda: exx(tb8))
    ex_b_b8_button.grid(row=1, column=7, padx=1,sticky=tk.E)
    ex_b_b9_label = tk.Label(ex_b_1_frame, text='⑨南非幣(ZAR)<-NT$', font=('',14))
    ex_b_b9_label.grid(row=2, column=0,sticky=tk.E)
    ex_b_b9_button = tk.Button(ex_b_1_frame, text=tb9, command=lambda: exx(tb9))
    ex_b_b9_button.grid(row=2, column=1, padx=1,sticky=tk.E)
    ex_b_b10_label = tk.Label(ex_b_1_frame, text='⑩瑞典幣(SEK)<-NT$', font=('',14))
    ex_b_b10_label.grid(row=2, column=2,sticky=tk.E)
    ex_b_b10_button = tk.Button(ex_b_1_frame, text=tb10, command=lambda: exx(tb10))
    ex_b_b10_button.grid(row=2, column=3, padx=1,sticky=tk.E)
    ex_b_b11_label = tk.Label(ex_b_1_frame, text='⑪紐元(NZD)<-NT$', font=('',14))
    ex_b_b11_label.grid(row=2, column=4,sticky=tk.E)
    ex_b_b11_button = tk.Button(ex_b_1_frame, text=tb11, command=lambda: exx(tb11))
    ex_b_b11_button.grid(row=2, column=5, padx=1,sticky=tk.E)
    ex_b_b12_label = tk.Label(ex_b_1_frame, text='⑫泰幣(THB)<-NT$', font=('',14))
    ex_b_b12_label.grid(row=2, column=6,sticky=tk.E)
    ex_b_b12_button = tk.Button(ex_b_1_frame, text=tb12, command=lambda: exx(tb12))
    ex_b_b12_button.grid(row=2, column=7, padx=1,sticky=tk.E)
    ex_b_b13_label = tk.Label(ex_b_1_frame, text='⑬菲國比索(PHP)<-NT$', font=('',14))
    ex_b_b13_label.grid(row=3, column=0,sticky=tk.E)
    ex_b_b13_button = tk.Button(ex_b_1_frame, text=tb13, command=lambda: exx(tb13))
    ex_b_b13_button.grid(row=3, column=1, padx=1,sticky=tk.E)
    ex_b_b14_label = tk.Label(ex_b_1_frame, text='⑭印尼幣(IDR)<-NT$', font=('',14))
    ex_b_b14_label.grid(row=3, column=2,sticky=tk.E)
    ex_b_b14_button = tk.Button(ex_b_1_frame, text=tb14, command=lambda: exx(tb14))
    ex_b_b14_button.grid(row=3, column=3, padx=1,sticky=tk.E)
    ex_b_b15_label = tk.Label(ex_b_1_frame, text='⑮歐元(EUR)<-NT$', font=('',14))
    ex_b_b15_label.grid(row=3, column=4,sticky=tk.E)
    ex_b_b15_button = tk.Button(ex_b_1_frame, text=tb15, command=lambda: exx(tb15))
    ex_b_b15_button.grid(row=3, column=5, padx=1,sticky=tk.E)
    ex_b_b16_label = tk.Label(ex_b_1_frame, text='⑯韓元(KRW)<-NT$', font=('',14))
    ex_b_b16_label.grid(row=3, column=6,sticky=tk.E)
    ex_b_b16_button = tk.Button(ex_b_1_frame, text=tb16, command=lambda: exx(tb16))
    ex_b_b16_button.grid(row=3, column=7, padx=1,sticky=tk.E)
    ex_b_b17_label = tk.Label(ex_b_1_frame, text='⑰越南盾(VND)<-NT$', font=('',14))
    ex_b_b17_label.grid(row=4, column=0,sticky=tk.E)
    ex_b_b17_button = tk.Button(ex_b_1_frame, text=tb17, command=lambda: exx(tb17))
    ex_b_b17_button.grid(row=4, column=1, padx=1,sticky=tk.E)
    ex_b_b18_label = tk.Label(ex_b_1_frame, text='⑱馬來幣(MYR)<-NT$', font=('',14))
    ex_b_b18_label.grid(row=4, column=2,sticky=tk.E)
    ex_b_b18_button = tk.Button(ex_b_1_frame, text=tb18, command=lambda: exx(tb18))
    ex_b_b18_button.grid(row=4, column=3, padx=1,sticky=tk.E)
    ex_b_b19_label = tk.Label(ex_b_1_frame, text='⑲人民幣(CNY)<-NT$', font=('',14))
    ex_b_b19_label.grid(row=4, column=4,sticky=tk.E)
    ex_b_b19_button = tk.Button(ex_b_1_frame, text=tb19, command=lambda: exx(tb19))
    ex_b_b19_button.grid(row=4, column=5, padx=1,sticky=tk.E)

ex_t2f_frame = tk.Frame(window)
ex_t2f_frame.pack(side=tk.TOP)
space_label = tk.Label(ex_t2f_frame, text='    ', font=('',8))
space_label.grid(row=0, column=0, padx=1)

ex_t2f_label = tk.Label(ex_t2f_frame, text='新台幣：', font=('',14))
ex_t2f_label.grid(row=1, column=0, padx=2)
ex_t2f_entry = tk.Entry(ex_t2f_frame)
ex_t2f_entry.grid(row=2, column=0, padx=2)
calculate_ex = tk.Button(ex_t2f_frame, text='換匯', font=('',15), command=ex1)
calculate_ex.grid(row=3, column=0, padx=2)

ex_t2fb_label = tk.Label(ex_t2f_frame, text='欲換匯多少外幣：', font=('',14))
ex_t2fb_label.grid(row=1, column=1, padx=2)
ex_t2fb_entry = tk.Entry(ex_t2f_frame)
ex_t2fb_entry.grid(row=2, column=1, padx=2)
calculate_ex_b = tk.Button(ex_t2f_frame, text='換匯', font=('',15), command=ex1_b)
calculate_ex_b.grid(row=3, column=1, padx=2)


datam2=[re.sub(r".+本行買入 ([.0-9]+) .+$",r"\1",i) for i in data]
data2=list(zip(datac,datam2))
d = {}
for key, value in data2:
    if key not in d:
        d[key] = []
    d[key].append(value)
ex2_USD=float(d['USD'][0])
ex2_HKD=float(d['HKD'][0])
ex2_GBP=float(d['GBP'][0])
ex2_AUD=float(d['AUD'][0])
ex2_CAD=float(d['CAD'][0])
ex2_SGD=float(d['SGD'][0])
ex2_CHF=float(d['CHF'][0])
ex2_JPY=float(d['JPY'][0])
ex2_ZAR=float(d['ZAR'][0])
ex2_SEK=float(d['SEK'][0])
ex2_NZD=float(d['NZD'][0])
ex2_THB=float(d['THB'][0])
ex2_PHP=float(d['PHP'][0])
ex2_IDR=float(d['IDR'][0])
ex2_EUR=float(d['EUR'][0])
ex2_KRW=float(d['KRW'][0])
ex2_VND=float(d['VND'][0])
ex2_MYR=float(d['MYR'][0])
ex2_CNY=float(d['CNY'][0])

ex2_USD_1=z1(ex2_USD)
ex2_HKD_1=z1(ex2_HKD)
ex2_GBP_1=z1(ex2_GBP)
ex2_AUD_1=z1(ex2_AUD)
ex2_CAD_1=z1(ex2_CAD)
ex2_SGD_1=z1(ex2_SGD)
ex2_CHF_1=z1(ex2_CHF)
ex2_JPY_1=z1(ex2_JPY)
ex2_ZAR_1=z1(ex2_ZAR)
ex2_SEK_1=z1(ex2_SEK)
ex2_NZD_1=z1(ex2_NZD)
ex2_THB_1=z1(ex2_THB)
ex2_PHP_1=z1(ex2_PHP)
ex2_IDR_1=z1(ex2_IDR)
ex2_EUR_1=z1(ex2_EUR)
ex2_KRW_1=z1(ex2_KRW)
ex2_VND_1=z1(ex2_VND)
ex2_MYR_1=z1(ex2_MYR)
ex2_CNY_1=z1(ex2_CNY)

space_m_label = tk.Label(window, text='    ', font=('',16))
space_m_label.pack(side=tk.TOP)
efheader_label = tk.Label(window, text='《 臺灣銀行公告  現金匯率  本行買入價 》', font=('',16))
efheader_label.pack(side=tk.TOP)
efheader2_label = tk.Label(window, text='( 一元各國貨幣 您可賣多少新台幣給銀行 )', font=('',13))
efheader2_label.pack(side=tk.TOP)
space_label = tk.Label(window, text='    ', font=('',2))
space_label.pack(side=tk.TOP)
ef_frame = tk.Frame(window)
ef_frame.pack(side=tk.TOP)
ef1_label = tk.Label(ef_frame, text='①美金(USD)：NT$', font=('',14))
ef1_label.grid(row=0, column=0,sticky=tk.E)
ef1_button = tk.Button(ef_frame, text=ex2_USD_1, command=lambda: exx(ex2_USD_1))
ef1_button.grid(row=0, column=1, padx=1,sticky=tk.E)
ef2_label = tk.Label(ef_frame, text='②港幣(HKD)：NT$', font=('',14))
ef2_label.grid(row=0, column=2,sticky=tk.E)
ef2_button = tk.Button(ef_frame, text=ex2_HKD_1, command=lambda: exx(ex2_HKD_1))
ef2_button.grid(row=0, column=3, padx=1,sticky=tk.E)
ef3_label = tk.Label(ef_frame, text='③英鎊(GBP)：NT$', font=('',14))
ef3_label.grid(row=0, column=4,sticky=tk.E)
ef3_button = tk.Button(ef_frame, text=ex2_GBP_1, command=lambda: exx(ex2_GBP_1))
ef3_button.grid(row=0, column=5, padx=1,sticky=tk.E)
ef4_label = tk.Label(ef_frame, text='④澳幣(AUD)：NT$', font=('',14))
ef4_label.grid(row=0, column=6,sticky=tk.E)
ef4_button = tk.Button(ef_frame, text=ex2_AUD_1, command=lambda: exx(ex2_AUD_1))
ef4_button.grid(row=0, column=7, padx=1,sticky=tk.E)
ef5_label = tk.Label(ef_frame, text='⑤加拿大幣(CAD)：NT$', font=('',14))
ef5_label.grid(row=1, column=0,sticky=tk.E)
ef5_button = tk.Button(ef_frame, text=ex2_CAD_1, command=lambda: exx(ex2_CAD_1))
ef5_button.grid(row=1, column=1, padx=1,sticky=tk.E)
ef6_label = tk.Label(ef_frame, text='⑥新加坡幣(SGD)：NT$', font=('',14))
ef6_label.grid(row=1, column=2,sticky=tk.E)
ef6_button = tk.Button(ef_frame, text=ex2_SGD_1, command=lambda: exx(ex2_SGD_1))
ef6_button.grid(row=1, column=3, padx=1,sticky=tk.E)
ef7_label = tk.Label(ef_frame, text='⑦瑞士法郎(CHF)：NT$', font=('',14))
ef7_label.grid(row=1, column=4,sticky=tk.E)
ef7_button = tk.Button(ef_frame, text=ex2_CHF_1, command=lambda: exx(ex2_CHF_1))
ef7_button.grid(row=1, column=5, padx=1,sticky=tk.E)
ef8_label = tk.Label(ef_frame, text='⑧日圓(JPY)：NT$', font=('',14))
ef8_label.grid(row=1, column=6,sticky=tk.E)
ef8_button = tk.Button(ef_frame, text=ex2_JPY_1, command=lambda: exx(ex2_JPY_1))
ef8_button.grid(row=1, column=7, padx=1,sticky=tk.E)
ef9_label = tk.Label(ef_frame, text='⑨南非幣(ZAR)：NT$', font=('',14))
ef9_label.grid(row=2, column=0,sticky=tk.E)
ef9_button = tk.Button(ef_frame, text=ex2_ZAR_1, command=lambda: exx(ex2_ZAR_1))
ef9_button.grid(row=2, column=1, padx=1,sticky=tk.E)
ef10_label = tk.Label(ef_frame, text='⑩瑞典幣(SEK)：NT$', font=('',14))
ef10_label.grid(row=2, column=2,sticky=tk.E)
ef10_button = tk.Button(ef_frame, text=ex2_SEK_1, command=lambda: exx(ex2_SEK_1))
ef10_button.grid(row=2, column=3, padx=1,sticky=tk.E)
ef11_label = tk.Label(ef_frame, text='⑪紐元(NZD)：NT$', font=('',14))
ef11_label.grid(row=2, column=4,sticky=tk.E)
ef11_button = tk.Button(ef_frame, text=ex2_NZD_1, command=lambda: exx(ex2_NZD_1))
ef11_button.grid(row=2, column=5, padx=1,sticky=tk.E)
ef12_label = tk.Label(ef_frame, text='⑫泰幣(THB)：NT$', font=('',14))
ef12_label.grid(row=2, column=6,sticky=tk.E)
ef12_button = tk.Button(ef_frame, text=ex2_THB_1, command=lambda: exx(ex2_THB_1))
ef12_button.grid(row=2, column=7, padx=1,sticky=tk.E)
ef13_label = tk.Label(ef_frame, text='⑬菲國比索(PHP)：NT$', font=('',14))
ef13_label.grid(row=3, column=0,sticky=tk.E)
ef13_button = tk.Button(ef_frame, text=ex2_PHP_1, command=lambda: exx(ex2_PHP_1))
ef13_button.grid(row=3, column=1, padx=1,sticky=tk.E)
ef14_label = tk.Label(ef_frame, text='⑭印尼幣(IDR)：NT$', font=('',14))
ef14_label.grid(row=3, column=2,sticky=tk.E)
ef14_button = tk.Button(ef_frame, text=ex2_IDR_1, command=lambda: exx(ex2_IDR_1))
ef14_button.grid(row=3, column=3, padx=1,sticky=tk.E)
ef15_label = tk.Label(ef_frame, text='⑮歐元(EUR)：NT$', font=('',14))
ef15_label.grid(row=3, column=4,sticky=tk.E)
ef15_button = tk.Button(ef_frame, text=ex2_EUR_1, command=lambda: exx(ex2_EUR_1))
ef15_button.grid(row=3, column=5, padx=1,sticky=tk.E)
ef16_label = tk.Label(ef_frame, text='⑯韓元(KRW)：NT$', font=('',14))
ef16_label.grid(row=3, column=6,sticky=tk.E)
ef16_button = tk.Button(ef_frame, text=ex2_KRW_1, command=lambda: exx(ex2_KRW_1))
ef16_button.grid(row=3, column=7, padx=1,sticky=tk.E)
ef17_label = tk.Label(ef_frame, text='⑰越南盾(VND)：NT$', font=('',14))
ef17_label.grid(row=4, column=0,sticky=tk.E)
ef17_button = tk.Button(ef_frame, text=ex2_VND_1, command=lambda: exx(ex2_VND_1))
ef17_button.grid(row=4, column=1, padx=1,sticky=tk.E)
ef18_label = tk.Label(ef_frame, text='⑱馬來幣(MYR)：NT$', font=('',14))
ef18_label.grid(row=4, column=2,sticky=tk.E)
ef18_button = tk.Button(ef_frame, text=ex2_MYR_1, command=lambda: exx(ex2_MYR_1))
ef18_button.grid(row=4, column=3, padx=1,sticky=tk.E)
ef19_label = tk.Label(ef_frame, text='⑲人民幣(CNY)：NT$', font=('',14))
ef19_label.grid(row=4, column=4,sticky=tk.E)
ef19_button = tk.Button(ef_frame, text=ex2_CNY_1, command=lambda: exx(ex2_CNY_1))
ef19_button.grid(row=4, column=5, padx=1,sticky=tk.E)


def ex2():
    money2=float(ex_f2t_entry.get())
    f1=z3(money2,ex2_USD)
    f2=z3(money2,ex2_HKD)
    f3=z3(money2,ex2_GBP)
    f4=z3(money2,ex2_AUD)
    f5=z3(money2,ex2_CAD)
    f6=z3(money2,ex2_SGD)
    f7=z3(money2,ex2_CHF)
    f8=z3(money2,ex2_JPY)
    f9=z3(money2,ex2_ZAR)
    f10=z3(money2,ex2_SEK)
    f11=z3(money2,ex2_NZD)
    f12=z3(money2,ex2_THB)
    f13=z3(money2,ex2_PHP)
    f14=z3(money2,ex2_IDR)
    f15=z3(money2,ex2_EUR)
    f16=z3(money2,ex2_KRW)
    f17=z3(money2,ex2_VND)
    f18=z3(money2,ex2_MYR)
    f19=z3(money2,ex2_CNY)
    window3 = tk.Tk()
    window3.title('外幣 換成 新台幣')
    window3.geometry('1000x205')
    window3.configure(background='white')
    space_ex2_label = tk.Label(window3, text='    ', font=('',7))
    space_ex2_label.pack(side=tk.TOP)
    fheader_label = tk.Label(window3, text='外幣金額：'+ex_f2t_entry.get()+'元  可換多少新台幣', font=('',21))
    fheader_label.pack()
    space_ex2_label = tk.Label(window3, text='    ', font=('',7))
    space_ex2_label.pack(side=tk.TOP)
    f_frame = tk.Frame(window3)
    f_frame.pack(side=tk.TOP)
    ex_f1_label = tk.Label(f_frame, text='①美金(USD)->NT$', font=('',14))
    ex_f1_label.grid(row=0, column=0,sticky=tk.E)
    ex_f1_button = tk.Button(f_frame, text=f1, command=lambda: exx(f1))
    ex_f1_button.grid(row=0, column=1, padx=1,sticky=tk.E)
    ex_f2_label = tk.Label(f_frame, text='②港幣(HKD)->NT$', font=('',14))
    ex_f2_label.grid(row=0, column=2,sticky=tk.E)
    ex_f2_button = tk.Button(f_frame, text=f2, command=lambda: exx(f2))
    ex_f2_button.grid(row=0, column=3, padx=1,sticky=tk.E)
    ex_f3_label = tk.Label(f_frame, text='③英鎊(GBP)->NT$', font=('',14))
    ex_f3_label.grid(row=0, column=4,sticky=tk.E)
    ex_f3_button = tk.Button(f_frame, text=f3, command=lambda: exx(f3))
    ex_f3_button.grid(row=0, column=5, padx=1,sticky=tk.E)
    ex_f4_label = tk.Label(f_frame, text='④澳幣(AUD)->NT$', font=('',14))
    ex_f4_label.grid(row=0, column=6,sticky=tk.E)
    ex_f4_button = tk.Button(f_frame, text=f4, command=lambda: exx(f4))
    ex_f4_button.grid(row=0, column=7, padx=1,sticky=tk.E)
    ex_f5_label = tk.Label(f_frame, text='⑤加拿大幣(CAD)->NT$', font=('',14))
    ex_f5_label.grid(row=1, column=0,sticky=tk.E)
    ex_f5_button = tk.Button(f_frame, text=f5, command=lambda: exx(f5))
    ex_f5_button.grid(row=1, column=1, padx=1,sticky=tk.E)
    ex_f6_label = tk.Label(f_frame, text='⑥新加坡幣(SGD)->NT$', font=('',14))
    ex_f6_label.grid(row=1, column=2,sticky=tk.E)
    ex_f6_button = tk.Button(f_frame, text=f6, command=lambda: exx(f6))
    ex_f6_button.grid(row=1, column=3, padx=1,sticky=tk.E)
    ex_f7_label = tk.Label(f_frame, text='⑦瑞士法郎(CHF)->NT$', font=('',14))
    ex_f7_label.grid(row=1, column=4,sticky=tk.E)
    ex_f7_button = tk.Button(f_frame, text=f7, command=lambda: exx(f7))
    ex_f7_button.grid(row=1, column=5, padx=1,sticky=tk.E)
    ex_f8_label = tk.Label(f_frame, text='⑧日圓(JPY)->NT$', font=('',14))
    ex_f8_label.grid(row=1, column=6,sticky=tk.E)
    ex_f8_button = tk.Button(f_frame, text=f8, command=lambda: exx(f8))
    ex_f8_button.grid(row=1, column=7, padx=1,sticky=tk.E)
    ex_f9_label = tk.Label(f_frame, text='⑨南非幣(ZAR)->NT$', font=('',14))
    ex_f9_label.grid(row=2, column=0,sticky=tk.E)
    ex_f9_button = tk.Button(f_frame, text=f9, command=lambda: exx(f9))
    ex_f9_button.grid(row=2, column=1, padx=1,sticky=tk.E)
    ex_f10_label = tk.Label(f_frame, text='⑩瑞典幣(SEK)->NT$', font=('',14))
    ex_f10_label.grid(row=2, column=2,sticky=tk.E)
    ex_f10_button = tk.Button(f_frame, text=f10, command=lambda: exx(f10))
    ex_f10_button.grid(row=2, column=3, padx=1,sticky=tk.E)
    ex_f11_label = tk.Label(f_frame, text='⑪紐元(NZD)->NT$', font=('',14))
    ex_f11_label.grid(row=2, column=4,sticky=tk.E)
    ex_f11_button = tk.Button(f_frame, text=f11, command=lambda: exx(f11))
    ex_f11_button.grid(row=2, column=5, padx=1,sticky=tk.E)
    ex_f12_label = tk.Label(f_frame, text='⑫泰幣(THB)->NT$', font=('',14))
    ex_f12_label.grid(row=2, column=6,sticky=tk.E)
    ex_f12_button = tk.Button(f_frame, text=f12, command=lambda: exx(f12))
    ex_f12_button.grid(row=2, column=7, padx=1,sticky=tk.E)
    ex_f13_label = tk.Label(f_frame, text='⑬菲國比索(PHP)->NT$', font=('',14))
    ex_f13_label.grid(row=3, column=0,sticky=tk.E)
    ex_f13_button = tk.Button(f_frame, text=f13, command=lambda: exx(f13))
    ex_f13_button.grid(row=3, column=1, padx=1,sticky=tk.E)
    ex_f14_label = tk.Label(f_frame, text='⑭印尼幣(IDR)->NT$', font=('',14))
    ex_f14_label.grid(row=3, column=2,sticky=tk.E)
    ex_f14_button = tk.Button(f_frame, text=f14, command=lambda: exx(f14))
    ex_f14_button.grid(row=3, column=3, padx=1,sticky=tk.E)
    ex_f15_label = tk.Label(f_frame, text='⑮歐元(EUR)->NT$', font=('',14))
    ex_f15_label.grid(row=3, column=4,sticky=tk.E)
    ex_f15_button = tk.Button(f_frame, text=f15, command=lambda: exx(f15))
    ex_f15_button.grid(row=3, column=5, padx=1,sticky=tk.E)
    ex_f16_label = tk.Label(f_frame, text='⑯韓元(KRW)->NT$', font=('',14))
    ex_f16_label.grid(row=3, column=6,sticky=tk.E)
    ex_f16_button = tk.Button(f_frame, text=f16, command=lambda: exx(f16))
    ex_f16_button.grid(row=3, column=7, padx=1,sticky=tk.E)
    ex_f17_label = tk.Label(f_frame, text='⑰越南盾(VND)->NT$', font=('',14))
    ex_f17_label.grid(row=4, column=0,sticky=tk.E)
    ex_f17_button = tk.Button(f_frame, text=f17, command=lambda: exx(f17))
    ex_f17_button.grid(row=4, column=1, padx=1,sticky=tk.E)
    ex_f18_label = tk.Label(f_frame, text='⑱馬來幣(MYR)->NT$', font=('',14))
    ex_f18_label.grid(row=4, column=2,sticky=tk.E)
    ex_f18_button = tk.Button(f_frame, text=f18, command=lambda: exx(f18))
    ex_f18_button.grid(row=4, column=3, padx=1,sticky=tk.E)
    ex_f19_label = tk.Label(f_frame, text='⑲人民幣(CNY)->NT$', font=('',14))
    ex_f19_label.grid(row=4, column=4,sticky=tk.E)
    ex_f19_button = tk.Button(f_frame, text=f19, command=lambda: exx(f19))
    ex_f19_button.grid(row=4, column=5, padx=1,sticky=tk.E)


def ex2_b():
    money2_b=float(ex_f2tb_entry.get())
    fb1=z2(ex2_USD,money2_b)
    fb2=z2(ex2_HKD,money2_b)
    fb3=z2(ex2_GBP,money2_b)
    fb4=z2(ex2_AUD,money2_b)
    fb5=z2(ex2_CAD,money2_b)
    fb6=z2(ex2_SGD,money2_b)
    fb7=z2(ex2_CHF,money2_b)
    fb8=z2(ex2_JPY,money2_b)
    fb9=z2(ex2_ZAR,money2_b)
    fb10=z2(ex2_SEK,money2_b)
    fb11=z2(ex2_NZD,money2_b)
    fb12=z2(ex2_THB,money2_b)
    fb13=z2(ex2_PHP,money2_b)
    fb14=z2(ex2_IDR,money2_b)
    fb15=z2(ex2_EUR,money2_b)
    fb16=z2(ex2_KRW,money2_b)
    fb17=z2(ex2_VND,money2_b)
    fb18=z2(ex2_MYR,money2_b)
    fb19=z2(ex2_CNY,money2_b)
    window3_2 = tk.Tk()
    window3_2.title('外幣 換成 新台幣')
    window3_2.geometry('1000x205')
    window3_2.configure(background='white')
    space_ex2_b_label = tk.Label(window3_2, text='    ', font=('',7))
    space_ex2_b_label.pack(side=tk.TOP)
    fheader_b_label = tk.Label(window3_2, text='欲換回新台幣：'+ex_f2tb_entry.get()+'元  需要多少外幣', font=('',21))
    fheader_b_label.pack()
    space_ex2_b_label = tk.Label(window3_2, text='    ', font=('',7))
    space_ex2_b_label.pack(side=tk.TOP)
    f_b_frame = tk.Frame(window3_2)
    f_b_frame.pack(side=tk.TOP)
    ex_b_b_f1_label = tk.Label(f_b_frame, text='①美金(USD) $', font=('',14))
    ex_b_b_f1_label.grid(row=0, column=0,sticky=tk.E)
    ex_b_b_f1_button = tk.Button(f_b_frame, text=fb1, command=lambda: exx(fb1))
    ex_b_b_f1_button.grid(row=0, column=1, padx=1,sticky=tk.E)
    ex_b_f2_label = tk.Label(f_b_frame, text='②港幣(HKD) $', font=('',14))
    ex_b_f2_label.grid(row=0, column=2,sticky=tk.E)
    ex_b_f2_button = tk.Button(f_b_frame, text=fb2, command=lambda: exx(fb2))
    ex_b_f2_button.grid(row=0, column=3, padx=1,sticky=tk.E)
    ex_b_f3_label = tk.Label(f_b_frame, text='③英鎊(GBP) £', font=('',14))
    ex_b_f3_label.grid(row=0, column=4,sticky=tk.E)
    ex_b_f3_button = tk.Button(f_b_frame, text=fb3, command=lambda: exx(fb3))
    ex_b_f3_button.grid(row=0, column=5, padx=1,sticky=tk.E)
    ex_b_f4_label = tk.Label(f_b_frame, text='④澳幣(AUD) $', font=('',14))
    ex_b_f4_label.grid(row=0, column=6,sticky=tk.E)
    ex_b_f4_button = tk.Button(f_b_frame, text=fb4, command=lambda: exx(fb4))
    ex_b_f4_button.grid(row=0, column=7, padx=1,sticky=tk.E)
    ex_b_f5_label = tk.Label(f_b_frame, text='⑤加拿大幣(CAD) $', font=('',14))
    ex_b_f5_label.grid(row=1, column=0,sticky=tk.E)
    ex_b_f5_button = tk.Button(f_b_frame, text=fb5, command=lambda: exx(fb5))
    ex_b_f5_button.grid(row=1, column=1, padx=1,sticky=tk.E)
    ex_b_f6_label = tk.Label(f_b_frame, text='⑥新加坡幣(SGD) $', font=('',14))
    ex_b_f6_label.grid(row=1, column=2,sticky=tk.E)
    ex_b_f6_button = tk.Button(f_b_frame, text=fb6, command=lambda: exx(fb6))
    ex_b_f6_button.grid(row=1, column=3, padx=1,sticky=tk.E)
    ex_b_f7_label = tk.Label(f_b_frame, text='⑦瑞士法郎(CHF) ₣', font=('',14))
    ex_b_f7_label.grid(row=1, column=4,sticky=tk.E)
    ex_b_f7_button = tk.Button(f_b_frame, text=fb7, command=lambda: exx(fb7))
    ex_b_f7_button.grid(row=1, column=5, padx=1,sticky=tk.E)
    ex_b_f8_label = tk.Label(f_b_frame, text='⑧日圓(JPY) ¥', font=('',14))
    ex_b_f8_label.grid(row=1, column=6,sticky=tk.E)
    ex_b_f8_button = tk.Button(f_b_frame, text=fb8, command=lambda: exx(fb8))
    ex_b_f8_button.grid(row=1, column=7, padx=1,sticky=tk.E)
    ex_b_f9_label = tk.Label(f_b_frame, text='⑨南非幣(ZAR) $', font=('',14))
    ex_b_f9_label.grid(row=2, column=0,sticky=tk.E)
    ex_b_f9_button = tk.Button(f_b_frame, text=fb9, command=lambda: exx(fb9))
    ex_b_f9_button.grid(row=2, column=1, padx=1,sticky=tk.E)
    ex_b_f10_label = tk.Label(f_b_frame, text='⑩瑞典幣(SEK) $', font=('',14))
    ex_b_f10_label.grid(row=2, column=2,sticky=tk.E)
    ex_b_f10_button = tk.Button(f_b_frame, text=fb10, command=lambda: exx(fb10))
    ex_b_f10_button.grid(row=2, column=3, padx=1,sticky=tk.E)
    ex_b_f11_label = tk.Label(f_b_frame, text='⑪紐元(NZD) $', font=('',14))
    ex_b_f11_label.grid(row=2, column=4,sticky=tk.E)
    ex_b_f11_button = tk.Button(f_b_frame, text=fb11, command=lambda: exx(fb11))
    ex_b_f11_button.grid(row=2, column=5, padx=1,sticky=tk.E)
    ex_b_f12_label = tk.Label(f_b_frame, text='⑫泰幣(THB) ฿', font=('',14))
    ex_b_f12_label.grid(row=2, column=6,sticky=tk.E)
    ex_b_f12_button = tk.Button(f_b_frame, text=fb12, command=lambda: exx(fb12))
    ex_b_f12_button.grid(row=2, column=7, padx=1,sticky=tk.E)
    ex_b_f13_label = tk.Label(f_b_frame, text='⑬菲國比索(PHP) ₱', font=('',14))
    ex_b_f13_label.grid(row=3, column=0,sticky=tk.E)
    ex_b_f13_button = tk.Button(f_b_frame, text=fb13, command=lambda: exx(fb13))
    ex_b_f13_button.grid(row=3, column=1, padx=1,sticky=tk.E)
    ex_b_f14_label = tk.Label(f_b_frame, text='⑭印尼幣(IDR) ₨', font=('',14))
    ex_b_f14_label.grid(row=3, column=2,sticky=tk.E)
    ex_b_f14_button = tk.Button(f_b_frame, text=fb14, command=lambda: exx(fb14))
    ex_b_f14_button.grid(row=3, column=3, padx=1,sticky=tk.E)
    ex_b_f15_label = tk.Label(f_b_frame, text='⑮歐元(EUR) €', font=('',14))
    ex_b_f15_label.grid(row=3, column=4,sticky=tk.E)
    ex_b_f15_button = tk.Button(f_b_frame, text=fb15, command=lambda: exx(fb15))
    ex_b_f15_button.grid(row=3, column=5, padx=1,sticky=tk.E)
    ex_b_f16_label = tk.Label(f_b_frame, text='⑯韓元(KRW) ₩', font=('',14))
    ex_b_f16_label.grid(row=3, column=6,sticky=tk.E)
    ex_b_f16_button = tk.Button(f_b_frame, text=fb16, command=lambda: exx(fb16))
    ex_b_f16_button.grid(row=3, column=7, padx=1,sticky=tk.E)
    ex_b_f17_label = tk.Label(f_b_frame, text='⑰越南盾(VND) ₫', font=('',14))
    ex_b_f17_label.grid(row=4, column=0,sticky=tk.E)
    ex_b_f17_button = tk.Button(f_b_frame, text=fb17, command=lambda: exx(fb17))
    ex_b_f17_button.grid(row=4, column=1, padx=1,sticky=tk.E)
    ex_b_f18_label = tk.Label(f_b_frame, text='⑱馬來幣(MYR) $', font=('',14))
    ex_b_f18_label.grid(row=4, column=2,sticky=tk.E)
    ex_b_f18_button = tk.Button(f_b_frame, text=fb18, command=lambda: exx(fb18))
    ex_b_f18_button.grid(row=4, column=3, padx=1,sticky=tk.E)
    ex_b_f19_label = tk.Label(f_b_frame, text='⑲人民幣(CNY) ¥', font=('',14))
    ex_b_f19_label.grid(row=4, column=4,sticky=tk.E)
    ex_b_f19_button = tk.Button(f_b_frame, text=fb19, command=lambda: exx(fb19))
    ex_b_f19_button.grid(row=4, column=5, padx=1,sticky=tk.E)

ex_f2t_frame = tk.Frame(window)
ex_f2t_frame.pack(side=tk.TOP)
space2_label = tk.Label(ex_f2t_frame, text='    ', font=('',8))
space2_label.grid(row=0, column=0, padx=1)

ex_f2t_label = tk.Label(ex_f2t_frame, text='外幣金額：', font=('',14))
ex_f2t_label.grid(row=1, column=0, padx=2)
ex_f2t_entry = tk.Entry(ex_f2t_frame)
ex_f2t_entry.grid(row=2, column=0, padx=2)
calculate_exf = tk.Button(ex_f2t_frame, text='換匯', font=('',15), command=ex2)
calculate_exf.grid(row=3, column=0, padx=2)

ex_f2tb_label = tk.Label(ex_f2t_frame, text='欲換匯多少新台幣：', font=('',14))
ex_f2tb_label.grid(row=1, column=1, padx=2)
ex_f2tb_entry = tk.Entry(ex_f2t_frame)
ex_f2tb_entry.grid(row=2, column=1, padx=2)
calculate_exf_b = tk.Button(ex_f2t_frame, text='換匯', font=('',15), command=ex2_b)
calculate_exf_b.grid(row=3, column=1, padx=2)


window.mainloop()

